/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FaxDecoder {
  constructor(inputSampleRate: number, options: FaxDecoderOptions | undefined | null, onEvent: (arg: FaxDecodeNotification) => void)
  pushF32(input: Float32Array): boolean
  reset(): boolean
  markSignalLost(): boolean
  drain(): object
  finish(): object
  dispose(): object
  get queuedSamples(): number
}

export declare class FaxEncoder {
  constructor(pixels: Uint8Array, width: number, height: number, spec: FaxSpecOptions, sampleRate: number, options?: FaxEncoderOptions | undefined | null)
  readSamples(maxSamples: number): object
  dispose(): object
  get isFinished(): boolean
  get progress(): FaxEncoderProgressSnapshot
}

export declare class SstvDecoder {
  constructor(inputSampleRate: number, options: SstvDecoderOptions | undefined | null, onEvent: (arg: SstvDecodeNotification) => void)
  pushF32(input: Float32Array): boolean
  reset(): boolean
  markDiscontinuity(droppedInputSamples: number): boolean
  drain(): object
  finish(): object
  dispose(): object
  get queuedSamples(): number
  get syncState(): string
}

export declare class SstvEncoder {
  constructor(pixels: Uint8Array, mode: JsSstvMode, sampleRate: number, options?: SstvEncoderOptions | undefined | null)
  readSamples(maxSamples: number): object
  dispose(): object
  get isFinished(): boolean
  get progress(): EncoderProgressSnapshot
}

export interface EncoderProgressSnapshot {
  samplesEmitted: number
  estimatedTotalSamples: number
  currentRow?: number
  finished: boolean
}

export interface FaxDecodeNotification {
  type: string
  pageId?: number
  paperId?: number
  boundaryId?: number
  ioc?: JsFaxIoc
  lpm?: number
  width?: number
  activeWidth?: number
  modulation?: string
  lineIndex?: number
  segmentLineIndex?: number
  pixels?: Uint8Array
  lines?: number
  partial?: boolean
  reason?: string
  boundaryKind?: string
  trusted?: boolean
  startLine?: number
  endLine?: number
}

export interface FaxDecoderOptions {
  outputMode?: string
  continuousAuto?: boolean
  autoAmModulation?: FaxModulationOptions
  immediateDecode?: boolean
  ioc?: FaxIoc
  lpm?: number
  modulation?: FaxModulationOptions
  maxLines?: number
  amFullScale?: number
  expectedPhasingSeconds?: number
  aptConfirmSeconds?: number
  acquisitionTimeoutSeconds?: number
  stopConfirmSeconds?: number
  signalLossSeconds?: number
  minimumSignalLevel?: number
  minimumCarrierCoherence?: number
  queueCapacitySamples?: number
}

export interface FaxEncoderOptions {
  amplitude?: number
  includeApt?: boolean
  includePhasing?: boolean
}

export interface FaxEncoderProgressSnapshot {
  samplesEmitted: number
  finished: boolean
}

export declare const enum FaxIoc {
  Ioc288 = 'ioc288',
  Ioc576 = 'ioc576'
}

export interface FaxModulationOptions {
  kind: string
  centerHz?: number
  deviationHz?: number
  polarity?: FaxPolarity
  carrierHz?: number
  blackLevel?: number
  whiteLevel?: number
}

export declare const enum FaxPolarity {
  Normal = 'normal',
  Inverted = 'inverted'
}

export interface FaxSpecOptions {
  ioc: FaxIoc
  lpm: number
  modulation?: FaxModulationOptions
  phasingSeconds?: number
  startSeconds?: number
  stopSeconds?: number
  trailingBlackSeconds?: number
  deadSectorFraction?: number
}

export interface SstvDecodeNotification {
  type: string
  imageId?: number
  paperId?: number
  boundaryId?: number
  mode?: JsSstvMode
  candidates?: Array<JsSstvMode>
  confidence?: number
  detection?: string
  visCode?: number
  ambiguous?: boolean
  candidateCount?: number
  frequencyOffsetHz?: number
  width?: number
  height?: number
  lineIndex?: number
  modeLineIndex?: number
  revision?: number
  completeness?: string
  pixels?: Uint8Array
  lines?: number
  lastLine?: number
  reason?: string
  boundaryKind?: string
  trusted?: boolean
  nominalHeight?: number
  startLine?: number
  endLine?: number
}

export interface SstvDecoderOptions {
  outputMode?: string
  fallbackMode?: SstvMode
  immediateDecode?: boolean
  detectVis?: boolean
  detectSyncTiming?: boolean
  manualMode?: SstvMode
  minimumSignalLevel?: number
  queueCapacitySamples?: number
}

export interface SstvEncoderOptions {
  amplitude?: number
  toneOffsetHz?: number
  includeVisHeader?: boolean
}

export declare const enum SstvMode {
  Robot8Bw = 'robot8Bw',
  Robot12Bw = 'robot12Bw',
  Robot24Bw = 'robot24Bw',
  Robot36Bw = 'robot36Bw',
  Robot12 = 'robot12',
  Robot24 = 'robot24',
  Robot36 = 'robot36',
  Robot72 = 'robot72',
  Martin1 = 'martin1',
  Martin2 = 'martin2',
  Martin3 = 'martin3',
  Martin4 = 'martin4',
  Scottie1 = 'scottie1',
  Scottie2 = 'scottie2',
  Scottie3 = 'scottie3',
  Scottie4 = 'scottie4',
  ScottieDx = 'scottieDx',
  Pd50 = 'pd50',
  Pd90 = 'pd90',
  Pd120 = 'pd120',
  Pd160 = 'pd160',
  Pd180 = 'pd180',
  Pd240 = 'pd240',
  Pd290 = 'pd290',
  WraaseSc2_30 = 'wraaseSc2_30',
  WraaseSc2_60 = 'wraaseSc2_60',
  WraaseSc2_120 = 'wraaseSc2_120',
  WraaseSc2_180 = 'wraaseSc2_180',
  Pasokon3 = 'pasokon3',
  Pasokon5 = 'pasokon5',
  Pasokon7 = 'pasokon7'
}

export interface SstvModeInfo {
  mode: SstvMode
  name: string
  visCode: number
  width: number
  height: number
  colorLayout: string
  scanLayout: string
  lineSeconds: number
  rowsPerLine: number
  status: string
}

export declare function sstvModes(): Array<SstvModeInfo>
